version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    command: postgres -c 'max_connections=1000'
    env_file:
      - .env
    ports:
      - 5432:5432 
